name: Build & Deploy Docker Image staging

on:
  push:
    branches: [ staging ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-build-deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Extract branch name
        id: current-branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Prepare
        run: |
          export BRANCH=${{ steps.current-branch.outputs.branch }}
          ./.github/fix-robots.sh
          ./.github/copy-env.sh

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build application
        run: CI=false npm run build

      - name: Create release asset
        run: zip -r build.zip build package.json package-lock.json README.md

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_TOKEN }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
